// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYHqFYcTSdBlb3t2yz4wxysNWs9NjNDE0',
    appId: '1:467903448150:web:6649d9ac35c1a6fa47e7f7',
    messagingSenderId: '467903448150',
    projectId: 'foodsurplus',
    authDomain: 'foodsurplus.firebaseapp.com',
    storageBucket: 'foodsurplus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlafeIE4_iJLU3Cq0E3C8F9e5Mwh4R4PM',
    appId: '1:467903448150:android:b5b5f54d5654f2a647e7f7',
    messagingSenderId: '467903448150',
    projectId: 'foodsurplus',
    storageBucket: 'foodsurplus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbakCg2ZOe91Ov2fYeYj7F-lVw7YVL6Yo',
    appId: '1:467903448150:ios:f07d144ffd3906be47e7f7',
    messagingSenderId: '467903448150',
    projectId: 'foodsurplus',
    storageBucket: 'foodsurplus.appspot.com',
    iosClientId: '467903448150-qiatvbgrq3qp0ldv7v5m83gf256m3ib4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wastenot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbakCg2ZOe91Ov2fYeYj7F-lVw7YVL6Yo',
    appId: '1:467903448150:ios:f07d144ffd3906be47e7f7',
    messagingSenderId: '467903448150',
    projectId: 'foodsurplus',
    storageBucket: 'foodsurplus.appspot.com',
    iosClientId: '467903448150-qiatvbgrq3qp0ldv7v5m83gf256m3ib4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wastenot',
  );
}
